name: bluesky-server
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - bluesky
  - pydm
  - typhos
  - bluesky-queueserver
  - bluesky-queueserver-api
  - tiled-client
  - tiled-server
  - suitcase-csv
  - suitcase-tiff
  - suitcase-mongo
  - pyqt
  - qtpy
  - p4p
  - bluesky-widgets
  - pip:
    - git+https://github.com/sfayfar/adl2pydm.git
