"""Shared processing defaults for the online and offline focus viewers."""

DEFAULT_FOCUS_MAX_WORKERS_TOTAL = 8
DEFAULT_FOCUS_BULK_WORKERS = 1
DEFAULT_FOCUS_FULL_WORKERS = 6
DEFAULT_FOCUS_FULL_CACHE_GB = 10.0
DEFAULT_FOCUS_PREPROCESS_MODE = "gamma"
DEFAULT_FOCUS_PREPROCESS_SIZE = 5
