# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/seanfayfar/GitHub/diffractometer-controls/diffractometer_controls/screens.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(934, 875)
        self.Frame1 = PyDMFrame(Form)
        self.Frame1.setGeometry(QtCore.QRect(310, 80, 261, 211))
        self.Frame1.setToolTip("")
        self.Frame1.setObjectName("Frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Frame1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(560, 480, 113, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
from pydm.widgets.frame import PyDMFrame
